baseurl = "https://prashgirdhar.com/"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
title = "Prashant Girdhar"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Personal Blog"
  #copyright = "&copy;2016 Your name or company"
  sidebarAbout = [
    "I use my blog to learn and play with different technologies. Feel free to get in touch.",
    "Originally from Auckland, currently based in Sydney."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  email         = "prash.girdhar@gmail.com"
  linkedin      = "https://www.linkedin.com/in/prashantgirdhar/"
  github        = "https://github.com/prashgirdhar"
