# Global settings applied to the whole site. Use -b $DEPLOY_PRIME_URL when there is no custom domain
[build]
  command = "hugo -t hugo-creative-portfolio-theme"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.55.5"

  