# Global settings applied to the whole site.
[build]
  command = "hugo -t hugo-creative-portfolio-theme -b $DEPLOY_PRIME_URL"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.55.5"

  