# Global settings applied to the whole site.  -b $DEPLOY_PRIME_URL
[build]
  command = "hugo -t hugo-creative-portfolio-theme"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.55.5"

  